version: '3.8'
services:
  ledger:
    image: "ghcr.io/formancehq/ledger:v1.8.1"
    healthcheck:
      test: ["CMD", "wget", "http://127.0.0.1:3068/_info", "-O", "-", "-q"]
      interval: 0.5s
      timeout: 5s
      retries: 20
    environment:
      NUMARY_SERVER_HTTP_BIND_ADDRESS: "0.0.0.0:3068"

  proxy:
    image: caddy:2
    depends_on:
      - ledger
    command: caddy reverse-proxy --from :3068 --to ledger:3068
    ports:
      - "3068:3068"
