version: '3.8'
services:
  app:
    command: yarn workspace temporal-worker start
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/working-dir
    restart: always
