version: '3'

services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.3
    ports:
      - 3567:3567
    environment:
      DISABLE_TELEMETRY: true
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 0.5s
      timeout: 5s
      retries: 20

networks:
  app_network:
    driver: bridge
