name: Build and test

on:
  pull_request:
    branches: ['main']

env:
  EXAMPLE_SECRET: example
  EXAMPLE_NAME: example
  REDWOOD_ENV_EXAMPLE: example

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # install all the dependencies
      - run: yarn install
      # Lint
      - run: yarn lint
      # build the redwood app to confirm it builds fine
      - run: yarn build
      # run the api tests
      - run: yarn test api --no-watch --silent
      # run the web tests
      - run: yarn test web --no-watch --silent
